# Generated by Django 5.0.2 on 2025-04-07 13:55

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('government_id', models.CharField(max_length=20, unique=True)),
                ('government_id_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('NATIONAL_ID', 'National ID'), ('DRIVERS_LICENSE', "Driver's License")], max_length=20)),
                ('address', models.TextField()),
                ('postal_code', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('is_eligible_voter', models.BooleanField(default=True)),
                ('verification_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Verified User',
                'verbose_name_plural': 'Verified Users',
                'db_table': 'verification_users',
                'db_tablespace': 'auth_db',
                'managed': True,
            },
        ),
    ]
