services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    restart: unless-stopped 
    env_file:
      - .env
  
  auth_db:
    image: postgres:15
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_AUTH_USER}
      - POSTGRES_PASSWORD=${DB_AUTH_PASSWORD}
      - POSTGRES_DB=${DB_AUTH_NAME}
    ports:
      - "5433:5432"
    env_file:
      - .env
    restart: unless-stopped
  
  ganache:
    image: trufflesuite/ganache:latest
    ports:
      - "8545:8545"
    command:
      - --deterministic
      - --chain.networkId=1337
      - --chain.chainId=1337
      - --miner.blockTime=0
      - --miner.instamine=eager
      - --wallet.defaultBalance=100
      - --accounts=10
      - --server.host=0.0.0.0
      - --database.dbPath=/ganache/data
    volumes:
      - ganache_data:/ganache/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - auth_db
      - ganache
    environment:
    - DB_HOST=db
    - DB_PORT=5432
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}
    - DB_NAME=${DB_NAME}
    - AUTH_DB_HOST=auth_db
    - AUTH_DB_PORT=5432
    - AUTH_DB_USER=${DB_AUTH_USER}
    - AUTH_DB_PASSWORD=${DB_AUTH_PASSWORD}
    - AUTH_DB_NAME=${DB_AUTH_NAME}
    - ETHEREUM_NODE_URL=http://ganache:8545
    - DEBUG=1
    env_file:
      - .env 

volumes:
  postgres_data:
  auth_postgres_data:
  ganache_data:
