# Generated by Django 5.0.2 on 2025-04-26 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.DeleteModel(
            name='Election',
        ),
    ]
