# Generated by Django 5.0.2 on 2025-04-16 13:11

import api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ethereum_private_key',
            field=api.fields.AESEncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='government_id',
            field=api.fields.AESEncryptedCharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=api.fields.AESEncryptedCharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=api.fields.AESEncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='government_id',
            field=api.fields.AESEncryptedCharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=api.fields.AESEncryptedCharField(max_length=50, unique=True),
        ),
    ]
