# Generated by Django 5.0.2 on 2025-04-18 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_update_field_sizes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['id']},
        ),
    ]
