# Generated by Django 5.0.2 on 2025-04-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_vote_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('site_name', models.CharField(default='DSP Voting System', max_length=100)),
                ('site_description', models.TextField(blank=True, default='A secure blockchain-based voting system')),
                ('contact_email', models.EmailField(default='admin@example.com', max_length=254)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True, default='System is currently under maintenance. Please check back later.')),
                ('min_candidates', models.IntegerField(default=2)),
                ('max_candidates', models.IntegerField(default=20)),
                ('require_verification', models.BooleanField(default=True)),
                ('allow_election_editing', models.BooleanField(default=True)),
                ('time_before_start_to_lock', models.IntegerField(default=24)),
                ('session_timeout', models.IntegerField(default=60)),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('password_expiry_days', models.IntegerField(default=90)),
                ('otp_expiry_minutes', models.IntegerField(default=15)),
                ('enforce_strong_passwords', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
