# Generated by Django 5.0.2 on 2025-04-26 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_vote_receipt_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='election',
            name='is_deployed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='election',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='election',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
