# Generated by Django 5.0.2 on 2025-04-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_election_updated_at_election_is_deployed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='nullification_admin_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='nullification_merkle_proof',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
