# Generated by Django 5.0.2 on 2025-04-29 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_vote_nullification_admin_response_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
    ]
