# Generated by Django 5.0.2 on 2025-04-30 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_vote_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='nullification_admin_response',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='nullification_approved_at',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='nullification_approved_by',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='nullification_merkle_proof',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='nullification_reason',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='nullification_rejected_at',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='nullification_rejected_by',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='nullification_rejection_reason',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='nullification_requested_at',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='nullification_status',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='nullification_transaction_hash',
        ),
    ]
